[env:esp32_s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    earlephilhower/ESP8266Audio @ 2.4.1